version: '3.5'
services:
  web:
    image: steveltn/https-portal:1
    container_name: ${HTTPS_PORTAL_CONTAINER_NAME}
    restart: always
    volumes:
      - ./nginx/ssl_certs:/var/lib/https-portal
      - ./nginx/conf/mysite_nginx.conf.temp:/etc/nginx/conf.d/mysite_nginx.conf.temp:ro
      - ./nginx/script/11-set-nginx-env:/etc/cont-init.d/11-set-nginx-env:ro
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params:ro
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env
    environment:
      DOMAINS: ${DOMAIN_NAME} -> http://${HTTPS_PORTAL_CONTAINER_NAME}:${NGINX_WATCH_PORT}/
      STAGE: 'production'
    depends_on:
      - django
  django:
    build: .
    container_name: ${DJANGO_CONTAINER_NAME}
    volumes:
      - .:/code
    expose:
      - ${DJANGO_CONTAINER_PORT}
    env_file:
      - .env
    command: uwsgi --socket :${DJANGO_CONTAINER_PORT} --module mysite.wsgi
