version: '3.5'
services:
  django:
    build:
      context: .
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
        - FTP_PROXY=$FTP_PROXY
        - ftp_proxy=$ftp_proxy
        - NO_PROXY=$NO_PROXY
        - no_proxy=$no_proxy
    container_name: ${DJANGO_CONTAINER_NAME}
    volumes:
      - .:/code
    expose:
      - ${DJANGO_CONTAINER_PORT}
    env_file:
      - .env
    command: uwsgi --socket :${DJANGO_CONTAINER_PORT} --module neoflowProject.wsgi --chdir /code
