version: '3.5'
services:
  web:
    build:
      context: .
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
        - FTP_PROXY=$FTP_PROXY
        - ftp_proxy=$ftp_proxy
        - NO_PROXY=$NO_PROXY
        - no_proxy=$no_proxy
    image: steveltn/https-portal:1
    container_name: ${HTTPS_PORTAL_CONTAINER_NAME}
    restart: always
    volumes:
      - ./nginx/ssl_certs:/var/lib/https-portal
      - ./nginx/conf/mysite_nginx.conf.temp:/etc/nginx/conf.d/mysite_nginx.conf.temp:ro
      - ./nginx/script/21-set-nginx-env:/etc/cont-init.d/21-set-nginx-env:ro
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params:ro
      - ./static:/static
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env
    environment:
      DOMAINS: ${DOMAIN_NAME} -> http://${HTTPS_PORTAL_CONTAINER_NAME}:${NGINX_WATCH_PORT}/
      STAGE: 'staging'
