# Generated by Django 2.2.26 on 2022-05-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MManpagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('distro', models.CharField(choices=[('qubes', 'Qubes OS'), ('parrot', 'Parrot OS'), ('kali', 'Kali Linux'), ('raspberrypi', 'Raspberry Pi OS'), ('centos', 'CentOS'), ('rhel', 'Red Hat Enterprise Linux'), ('debian', 'Debian Linux'), ('ubuntu', 'Ubuntu Linux')], max_length=50, verbose_name='ディストロ')),
            ],
        ),
    ]
