# Generated by Django 2.2.26 on 2022-05-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpage', '0003_manpagepost_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpagepost',
            name='version',
            field=models.FloatField(default=0, verbose_name='OS バージョン'),
        ),
    ]
