# Generated by Django 2.2.26 on 2022-05-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpage', '0004_auto_20220514_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpagepost',
            name='distro',
            field=models.CharField(choices=[('qubes', 'Qubes OS'), ('parrot', 'Parrot OS'), ('kali', 'Kali Linux'), ('raspberrypi', 'Raspberry Pi OS'), ('centos', 'CentOS'), ('rhel', 'Red Hat Enterprise Linux'), ('debian', 'Debian Linux'), ('ubuntu', 'Ubuntu Linux'), ('freebsd', 'FreeBSD')], max_length=50, verbose_name='ディストロ'),
        ),
    ]
